default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: your password
  socket: your socket

development:
  <<: *default
  database: your db

test:
  <<: *default
  database: your db

production:
  <<: *default
  database: your db
