default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Manhcute@258
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: timekeeping_dev

test:
  <<: *default
  database: timekeeping_test

production:
  <<: *default
  database: timekeeping_product
